title: "Varuni Singh"
description: "Data Science | Projects | Blog"
baseurl: ""
url: "https://varuni13.github.io"

# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"   # or "dark", "mint", "neon", "contrast"


# Plugins required
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

author:
  name: "Varuni Singh"
  avatar: "/assets/images/avatar.png"
  bio: "First-year eMasters student in Data Science at IIT Gandhinagar."


# Show navbar
header:
  overlay_color: "#000"
  overlay_filter: "0.5"
  show_overlay_excerpt: true
  show_nav: true

# Enable site-wide nav in header
minimal_mistakes_skin: "default"  # optional, for style
locale: "en-US"

# This is the key that was missing 
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
